name: CI/CD with Deploy, Discord Notification & Rollback

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install
      - run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install -g vercel@latest
      - run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Notify Discord on Success
        if: success() && needs.build.result == 'success'
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "✅ Deploy สำเร็จ!"
          description: "Deploy เสร็จเรียบร้อย"
          color: 0x2ECC71

      - name: Notify Discord on Build Failure
        if: needs.build.result == 'failure'
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content": "⚠️ Build ล้มเหลว แต่กำลังพยายาม Deploy ต่อ"}' \
          ${{ secrets.DISCORD_WEBHOOK }}
          - name: Rollback on Failure
          if: failure()
          run: |
            echo "Rollback to previous deployment..."
            vercel rollback --token=${{ secrets.VERCEL_TOKEN }} --yes
        
      - name: Notify Discord on Failure
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "❌ เกิดข้อผิดพลาดในการ Deploy!"
          description: "Rollback ไปเวอร์ชันก่อนหน้าเรียบร้อยแล้ว"
          color: 0xE74C3C