name: CI/CD with Error Handling and Discord Notification

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true  # ต่อไป deploy แม้ build error
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: always()  # รันเสมอแม้ build ล้มเหลว
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Pull Vercel Environment
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel (Production)
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}

      # แจ้ง Discord เมื่อ Deploy สำเร็จ
      - name: Notify Discord on Success
        if: success()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "✅ Deploy สำเร็จ!"
          description: "เว็บอัปเดตเรียบร้อยแล้ว!"
          color: 0x2ECC71

      # แจ้ง Discord เมื่อ Build หรือ Deploy ล้มเหลว
      - name: Notify Discord on Failure
        if: failure() || needs.build.result == 'failure'
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "❌ เกิดข้อผิดพลาดในการ Build หรือ Deploy!"
          description: "ตรวจสอบขั้นตอน CI/CD ด่วน!"
          color: 0xE74C3C