name: CI/CD with Deploy, Discord Notification & Code Rollback

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install -g vercel@latest
      - run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Notify Discord on Success
        if: success() && needs.build.result == 'success'
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "✅ Deploy สำเร็จ!"
          description: "Deploy เสร็จเรียบร้อย"
          color: 0x2ECC71

      - name: Rollback Deployment and Code on Failure
        if: failure()
        run: |
          echo "Rollback deployment on Vercel..."
          vercel rollback --token=${{ secrets.VERCEL_TOKEN }} --yes
          
          echo "Rollback Git commit..."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git reset --hard HEAD~1
          git push --force origin main
          
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"❌ Rollback ทั้ง deployment และ code ไป commit ก่อนหน้าเรียบร้อยแล้ว\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}
